### ISSUE TITLE
The script doesn't seem to work (for me) with the new version of the website.

### ISSUE THREAD

**Issue by jrikhal** [arekolek/DuolingoCourseSwitcher#6]
Duolingo is switching little by little all users to a new version of the website.
Like almost all userscript, this one seems to not work anymore with the new version.

**Comment by arekolek** [comment]
@jrikhal Thanks for the heads up. I don't have the new version yet, but I'll see what I can do once I do.

**Comment by franzalex** [comment]
@jrikhal I remember you posted an updated version script which works with the new version of the Duolingo website.

Could you please post a link to it here in this issue? That way, users coming here will be able to easily obtain the updated version.  
If creating a new repository is too long-winded, you can create a Gist (https://gist.github.com) and post the link here.

**Comment by arekolek** [comment]
@jrikhal @franzalex Can you guys post a screenshot of the new website here, in case it looks any different?

The reason I'm asking is that I went to Duolingo in incognito mode, because I think I read somewhere that they serve the new website to all new users. But it looked all the same to me. Is there anything different about how it looks? Or is it just some structure that changed, but not the presentation?

**Comment by franzalex** [comment]
@arekolek As you'll observe in the screenshot I have posted below, visually, the new site is practically indistinguishable from the old.

To my best of knowledge, it is the underlying workings that have been changed. The two I've observed are that (1) userscripts that require jQuery to run have to load their own versions at startup and (2) the `ajaxComplete` event does not get raised when the language is switched.

Of course, depending on the type of script you are designing / running, there may be other changes you'll have to take into consideration.

[![image](https://cloud.githubusercontent.com/assets/7560066/26764873/424a0e4c-495f-11e7-8fc2-ef475e3f9542.png)  
Click for full size][1]


 [1]: https://cloud.githubusercontent.com/assets/7560066/26764831/19e658a8-495e-11e7-889e-2c4a8230ab77.png "Click for full size"

**Comment by chrabia** [comment]
Any hope for an update?

**Comment by arekolek** [comment]
@chrabia I was actually working on an update last weekend. But I just found out that [Duolingo now supports this feature by default](https://www.duolingo.com/comment/23161515).

I'm thinking there's not much use for this script anymore, is there?

**Comment by chrabia** [comment]
Wow, you are right, they are supporting it!
Well, I still think that DuolingoCourseSwitcher had a lot better design, but you may be right, that it's not worth it.
